logging:
  level:
    org.javamoney: OFF
spring:
  messages:
    basename: exceptions
  datasource:
    url: jdbc:h2:file:./data/payments.db
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    open-in-view: true
